services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: library_app:latest
    container_name: library_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - laravel
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: library_app
      DB_USERNAME: admin
      DB_PASSWORD: thebestpassword8
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
        composer install --no-interaction --optimize-autoloader &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: mysql:8.1
    container_name: library_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: thebestpassword8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
